version: '3.0'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'True'
      UWSGI_HTTP: 0.0.0.0:8000
      UWSGI_MODULE: focus.server
      UWSGI_CALLABLE: application
      UWSGI_MASTER: 1
      UWSGI_BUFFER_SIZE: 32768
      FOCUS_USERNAME: ${FOCUS_USERNAME}
      FOCUS_PASSWORD: ${FOCUS_PASSWORD}
      FOCUS_WSDL: ${FOCUS_WSDL}
      FOCUS_CERTIFICATE: ${FOCUS_CERTIFICATE}
      TMA_CERTIFICATE: ${TMA_CERTIFICATE}
